/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import modelo.Docente;

/**
 *
 * @author josej
 */
public class frm_docente extends javax.swing.JFrame {
Docente docente;
DefaultTableModel tbl_model;
    /**
     * Creates new form frm_docente
     */
    public frm_docente() {
        initComponents();
        docente = new Docente();
        tbl_docentes.setModel(docente.leer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_codigo_docente = new javax.swing.JLabel();
        lbl_salario = new javax.swing.JLabel();
        lbl_fecha_ingreso_l = new javax.swing.JLabel();
        lbl_fecha_ingreso_r = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_codigo_docente = new javax.swing.JTextField();
        txt_salario = new javax.swing.JTextField();
        txt_fecha_ingreso_l = new javax.swing.JTextField();
        txt_fecha_ingreso_r = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        sp_docentes = new javax.swing.JScrollPane();
        tbl_docentes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_codigo_docente.setBackground(new java.awt.Color(51, 51, 255));
        lbl_codigo_docente.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_codigo_docente.setForeground(new java.awt.Color(255, 51, 51));
        lbl_codigo_docente.setText("codigo_docente");

        lbl_salario.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_salario.setForeground(new java.awt.Color(255, 51, 0));
        lbl_salario.setText("salario");

        lbl_fecha_ingreso_l.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_fecha_ingreso_l.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fecha_ingreso_l.setText("fecha_ingreso_laborar");

        lbl_fecha_ingreso_r.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_fecha_ingreso_r.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fecha_ingreso_r.setText("fecha_ingreso_registro");

        lbl_id.setText("0");

        txt_codigo_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo_docenteActionPerformed(evt);
            }
        });

        txt_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salarioActionPerformed(evt);
            }
        });

        txt_fecha_ingreso_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_ingreso_lActionPerformed(evt);
            }
        });

        txt_fecha_ingreso_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_ingreso_rActionPerformed(evt);
            }
        });

        btn_agregar.setFont(new java.awt.Font("Yu Gothic UI Light", 2, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(0, 0, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_borrar.setFont(new java.awt.Font("Yu Gothic UI Light", 2, 14)); // NOI18N
        btn_borrar.setForeground(new java.awt.Color(51, 51, 255));
        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Yu Gothic UI Light", 2, 14)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(51, 51, 255));
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        tbl_docentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_docentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_docentesMouseClicked(evt);
            }
        });
        tbl_docentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_docentesKeyReleased(evt);
            }
        });
        sp_docentes.setViewportView(tbl_docentes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp_docentes, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_agregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_codigo_docente)
                            .addComponent(lbl_fecha_ingreso_l)
                            .addComponent(lbl_fecha_ingreso_r)
                            .addComponent(lbl_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_editar)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_fecha_ingreso_l, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txt_fecha_ingreso_r)))
                            .addComponent(txt_codigo_docente)
                            .addComponent(txt_salario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrar)
                .addGap(228, 228, 228))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_id)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigo_docente)
                    .addComponent(txt_codigo_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_salario)
                    .addComponent(txt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha_ingreso_l)
                    .addComponent(txt_fecha_ingreso_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha_ingreso_r)
                    .addComponent(txt_fecha_ingreso_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_borrar)
                    .addComponent(btn_editar))
                .addGap(18, 18, 18)
                .addComponent(sp_docentes, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Docentes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigo_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo_docenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_docenteActionPerformed

    private void txt_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salarioActionPerformed

    private void txt_fecha_ingreso_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_ingreso_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_ingreso_lActionPerformed

    private void txt_fecha_ingreso_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_ingreso_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_ingreso_rActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        docente = new Docente(0,txt_codigo_docente.getText(),Integer.parseInt(txt_salario.getText()),txt_fecha_ingreso_l.getText(),txt_fecha_ingreso_r.getText());
        docente.crear();
        tbl_docentes.setModel(docente.leer());
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        docente = new Docente(Integer.parseInt(lbl_id.getText()), txt_codigo_docente.getText(), Double.parseDouble(txt_salario.getText()), txt_fecha_ingreso_l.getText(), txt_fecha_ingreso_r.getText());
        docente.editar();
        tbl_docentes.setModel(docente.leer());
        clear_datos();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
        docente = new Docente();
        docente.setId(Integer.parseInt(lbl_id.getText()));
        docente.borrar();
        tbl_docentes.setModel(docente.leer());
    }//GEN-LAST:event_btn_borrarActionPerformed
private void select_datos() {
    int fila = tbl_docentes.getSelectedRow();
    lbl_id.setText(tbl_docentes.getValueAt(fila, 0).toString());
    txt_codigo_docente.setText(tbl_docentes.getValueAt(fila, 1).toString());
    txt_salario.setText(tbl_docentes.getValueAt(fila, 2).toString());
    txt_fecha_ingreso_l.setText(tbl_docentes.getValueAt(fila, 3).toString());
    txt_fecha_ingreso_r.setText(tbl_docentes.getValueAt(fila, 4).toString());
}

    private void tbl_docentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_docentesMouseClicked
        // TODO add your handling code here:
        select_datos();
    }//GEN-LAST:event_tbl_docentesMouseClicked

    private void tbl_docentesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_docentesKeyReleased
        // TODO add your handling code here:
        select_datos();
    }//GEN-LAST:event_tbl_docentesKeyReleased
 public void clear_datos() {
        lbl_id.setText("");
        txt_codigo_docente.setText("");
        txt_salario.setText("");
        txt_fecha_ingreso_l.setText("");
        txt_fecha_ingreso_r.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_docente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_codigo_docente;
    private javax.swing.JLabel lbl_fecha_ingreso_l;
    private javax.swing.JLabel lbl_fecha_ingreso_r;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_salario;
    private javax.swing.JScrollPane sp_docentes;
    private javax.swing.JTable tbl_docentes;
    private javax.swing.JTextField txt_codigo_docente;
    private javax.swing.JTextField txt_fecha_ingreso_l;
    private javax.swing.JTextField txt_fecha_ingreso_r;
    private javax.swing.JTextField txt_salario;
    // End of variables declaration//GEN-END:variables
}
